name: fitness_center_sample
description: Fitness Center

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.1
  url_launcher: ^6.2.4
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - lib/Ekler/resimler/
    - lib/Ekler/iconlar/
    - lib/Ekler/iconlar/profil/